# Generated by Django 5.0.14 on 2025-06-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created',)},
        ),
    ]
